//
//  MedicineModel.swift
//  ApotechCare
//
//  Created by Prince Alvin Yusuf on 01/04/21.
//  Copyright © 2021 Muhammad Harviando. All rights reserved.
//

import Foundation

struct MedicineModel {
    
    let medicine: [Medicine] = [
        Medicine(image: "medicineOne", medicine: "Paracetamol", price: "Rp. 12.000", apotek: "Kimia Farma", medicineSummary: "Paracetamol 325 mg rasa strawberry", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineTwo", medicine: "Ibu Profen", price: "Rp. 15.000", apotek: "Janji Jiwa", medicineSummary: "Ibu Profen 325 mg rasa melon", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineThree", medicine: "Plantacid", price: "Rp. 30.000", apotek: "Kopi Kenangan", medicineSummary: "Paltacid 325 mg rasa melon", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineFour", medicine: "Oksitetrasiklin", price: "Rp. 50.000", apotek: "Poli Sehat", medicineSummary: "Oksitetrasiklin 325 mg rasa anggur", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineOne", medicine: "Vit-C", price: "Rp. 25.000", apotek: "BPJS", medicineSummary: "Paltacid 325 mg rasa paprika", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineTwo", medicine: "Alphara", price: "Rp. 10.000", apotek: "Kimia Farma", medicineSummary: "Alphara 325 mg rasa melon", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineThree", medicine: "CTM", price: "Rp. 100.000", apotek: "Kimia Farma", medicineSummary: "CTM 325 mg rasa timun", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineFour", medicine: "Dextral", price: "Rp. 250.000", apotek: "Moderna", medicineSummary: "Dextral 325 mg rasa mangga", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineOne", medicine: "Metaflu", price: "Rp. 210.000", apotek: "Moderna", medicineSummary: "Metaflu 325 mg rasa nangka", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineTwo", medicine: "Ambroxol", price: "Rp. 80.000", apotek: "Ibu Kandung", medicineSummary: "Paltacid 325 mg rasa pisang", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        Medicine(image: "medicineThree", medicine: "NewDiatab", price: "Rp. 120.000", apotek: "Sehat Jasmani", medicineSummary: "Paltacid 325 mg rasa jambu", description: "Meningkatkan risiko perdarahan, jika digunakan bersamaan dengan warfarin. \nMenurunkan efek paracetamol, jika digunakan dengan carbamazepine, phenytoin, phenobarbital, cholestyramine, dan imatinib. \nMeningkatkan efek samping obat busulfan. \nMeningkatkan kemungkinan munculnya efek samping paracetamol, jika digunakan dengan metoclopramide, domperidone, atau probenecid.", priceDeliver: [ "Rp. 10.000", "Rp. 20.000", "Rp. 30.0000" ]),
        
        
        
    ]
}
